### ISSUE TITLE
[GeoServer-GeoNode-ext] GWC property placeholder breaking plugins

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/geonode#271] opened 2017-10-20 13:18 UTC
GeoServer Property Placeholder and property gwc.prefix actually force to specify such property value to any plugin/extention willing to define its own Property Placeholder

**Comment by aaime** [comment] 2017-10-27 09:32
Is this not a duplicate of a monitoring one too?

**Comment by afabiani** [comment] 2017-10-27 09:36
Monitoring issue is a consequence of this which is more general. As a plugin making use of property placeholders currently Monitoring is also subjected to this.

**Comment by aaime** [comment] 2017-10-27 10:48
This should fix things:
https://github.com/geoserver/geoserver/pull/2612

**Closed** 2017-11-23 14:12 UTC
Labels: geoserver
