### ISSUE TITLE
Multiple emails sent erroneously when reloading resource page

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#468] opened 2020-04-09 15:47 UTC
As a document owner I reload it's detail page and four emails are sent out on each page reload:

- 2 "document has been published"
- 2 "document has been updated"

No messages are visible in the admin inbox, so it seems these emails are sent outside of the notification system.

![image](https://user-images.githubusercontent.com/571129/78913815-dc19ad80-7a89-11ea-8ee9-049a976a93e7.png)

**Comment by petrus7** [comment] 2020-04-10 07:12
It was caused by unnecessary Model.save in unesco 170. Closing it

**Closed by petrus7** 2020-04-10 07:12 UTC
Labels: bug
