### ISSUE TITLE
Cache misses on master demo

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#740] opened 2021-04-16 14:25 UTC
Apparently GWC is not working correctly on master demo. Although everything is configured (correctly to my eyes) we keep receiving cache misses for any layer.

The only trace I could fin from Geoserver logs was the followin:

![image](https://user-images.githubusercontent.com/571129/115038697-0e958c00-9ed0-11eb-9bae-ad681d21e37f.png)

**Comment by afabiani** [comment] 2021-04-16 15:56
@giohappy currently on master.demo there's something strange happening with the GWC gridsets.

When we upload a new layer, the gridsets bboxes are wrongly generated. By removing the default tailedlayer and recreating it from the geoserver gui, fixes the girdsets too.

See the differences here below:

![image](https://user-images.githubusercontent.com/1278021/115049577-2aeaf600-9edb-11eb-8f39-1a2dd9a26906.png)

Trying to save a tiledlayer with a broken grid, causes the following errors

![image](https://user-images.githubusercontent.com/1278021/115051357-0728af80-9edd-11eb-9e6e-f9e70fb3c693.png)

The layers with broken grids cause the following exception when asking for a tile

```
2021-04-16 15:51:25,106 INFO [org.geoserver.gwc] - Error dispatching tile request to GeoServer
org.geowebcache.grid.OutsideCoverageException: Coverage [minx,miny,maxx,maxy] is [64, 64, 63, 63, 7], index [x,y,z] is [35, 68, 7]
	at org.geowebcache.grid.GridSubset.checkCoverage(GridSubset.java:132)
	at org.geoserver.gwc.layer.GeoServerTileLayer.getTile(GeoServerTileLayer.java:579)
	at org.geoserver.gwc.GWC.dispatch(GWC.java:789)
	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:71)
	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:41)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy170.getMap(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor436.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:877)
	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:265)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:70)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:142)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:172)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:47)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by giohappy** [comment] 2021-04-16 17:02
@simboss this also happend on an instance of a client (you know who)

**Comment by afabiani** [comment] 2021-04-20 16:42
@giohappy @simboss it looks like the issue depends on an outdated GWC configuration shipped with the packaged GeoServer Data DIR.

I did few tests locally by cleanin up all the existing GWC configurations and let GeoServer re-create them. Then I changed back the default tiled layers values as before and saved.
After that, GWC started working as expected. The gridsets are correctly set even for newly uploaded layers.

Geolimits work and the GWC HITs are back

![image](https://user-images.githubusercontent.com/1278021/115433769-32c2d700-a208-11eb-9d3a-769c373c47d6.png)

**Comment by simboss** [comment] 2021-04-20 17:01
@afabiani what do you suggest we do for the server then?

**Comment by afabiani** [comment] 2021-04-21 08:03
Hello @simboss , specifically for master demo, but the same solution will work even for other servers affected by this issue, I would suggest to proceed as follows:

1. Stop Tomcat and physically delete from the DATA_DIR `gwc*` folders and files
2. Start Tomcat and let GeoServer recreate the correct GWC configuration and gridsets
3. Configure the default tile settings and global GWC settings
4. Configure the GWC diskquota
5. Recreate the TiledLayers

That fixes the issue for both old and new layers.

**Comment by giohappy** [comment] 2021-04-21 08:17
@simboss this is the plan:

 - fix the configuration inside the [geoserver-geonode-ext](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.18.x/geoserver/data/geonode_v218x) repo
 - tag a 2.18.2 geoserver-geonode-ext branch, since currently it's tagged as SNAPSHOT
 - fix Geoserver version to 2.18.2. Currently the image is tagged as 2.18.2 but in in reality it's using a [2.18.x build ](https://www.dropbox.com/s/xlich7pmneaupqp/geoserver-2.18.2}.war?dl=1)

**Comment by simboss** [comment] 2021-04-21 08:42
@giohappy @afabiani I am concerned about people who will upgrade and the relative confusion and noise that this will generate. We can tell everyone to do these steps.

I guess we can move forward with 3.2 and trying to replicate and fix this at the source with 3.2.1.

Opinions?

**Comment by giohappy** [comment] 2021-04-21 08:47
@simboss that's why I'd prefer to fix both GWC config and Geoserver version before the relase, because it will harder for users afterwards.

**Comment by simboss** [comment] 2021-04-21 08:53
@giohappy not sure what you mean, can you clarify?

**Comment by giohappy** [comment] 2021-04-21 08:59
@simboss excluding the deployments done by ourselves with 3.2.x, which will require a manusl fix, all the installs done with the upcoming stable 3.2 will be ok if we fix it before the release. 
If we fix it afterwards it will mean that any 3.2 install will need the manual procedure to fix it.

Am I wrong?

**Comment by simboss** [comment] 2021-04-21 09:14
maybe, it's me but it is not clear what you are suggesting.

>  I'd prefer to fix both GWC config and Geoserver version before the relase, because it will harder for users afterwards.

This means, to me, setting a specific version of GWC and GS. Not sure about the purpose.

> all the installs done with the upcoming stable 3.2 will be ok if we fix it before the release.
> If we fix it afterwards it will mean that any 3.2 install will need the manual procedure to fix it.

We fix what and by whom? You are implying that we ask a GS developer to investigate and fix the fact that gridset on new layer on GeoServer are wrong with the current GS config we ship with GeoNode? Or you are just happy with what @afabiani is proposing?

**Comment by giohappy** [comment] 2021-04-21 09:20
@simboss I assume that the fix propsed by @afabiani solve the issue. If you think that this should be investigated further ok, let's keep things as they are. A manual fix will be required in case (as reported by @afabiani)

**Comment by afabiani** [comment] 2021-04-21 09:22
@simboss @giohappy currently I have found a way to allow GeoNode fix automatically the gridsets bounds of GWC and therefore fix the Tiled Layer.

Basically, when a layer is created/updated GeoNode already sets the GWC parameters through the REST interface [here](https://github.com/GeoNode/geonode/blob/master/geonode/security/utils.py#L323)

I did test locally that by removing the default extents from the gridsets too and let GeoServer compute them dynamically, automatically fixes the issue. This implies basically to add very few lines of code on the previous method to just refresh the gridsets. That way we don't need to ask anyone to touch the GWC data dir or settings.

 ```python
               gwc_gridSubsets = tree.find('gridSubsets')
                tree.remove(gwc_gridSubsets)
                gwc_gridSubsets = etree.Element('gridSubsets')
                for gridSubset in ('EPSG:4326', 'EPSG:3857', 'EPSG:900913'):
                    gwc_gridSubset = etree.Element('gridSubset')
                    gwc_gridSetName = etree.Element('gridSetName')
                    gwc_gridSetName.text = gridSubset
                    gwc_gridSubset.append(gwc_gridSetName)
                    gwc_gridSubsets.append(gwc_gridSubset)

                tree.append(gwc_gridSubsets)
```

**Comment by giohappy** [comment] 2021-04-21 10:39
to recap @simboss:

- There's seem to be some problem in GWC with the bounds that it sets when a new TileLayer is created. I invite @afabiani to open an issue for this and describe what he has found and how it can be replicated. Apparently it doesn't happen always.
- The code snippat that @afabiani suggests to add to GeoNode forces GWC to recalculate the bounds corrently. The snippet removes the bounds from the TileLayer configuration, and when GWC recalculate them they are set correctly. I think we can introuce this code, which will fix any deployment, by the way the GEC issue must be investigated
- The code will be called from the `toggle_layer_cache` method. GeoNode uses this method to disable the caching for all formats if any geolimit rule is set for the layer. The end result is that the cache for a layer with geolimit is disabled (althought the TileLayer is not removed). As far as @afabiani explained to me this solution was implemented to avoid a cartesian product of GWC parameters (admitted that it's possible to use a Geofence LIMIT rule as a parameter, is it?).

For the moment I see the following plan:

 - introuce the snippet to "self-heal" the TileLayer bounds
 - open an issue to investigate what's wrong with GWC wrt to TileLayer bound configuration
 - eventually discuss any improvement to the way GWC is used when the geolimits are set

We agreed to keep Geoserver as it is (SNAPSHOT build) for the 3.2 release, otherwise we risk to introduce regressions.
We can dicuss the fixing of Geoserver version for GeoNode 3.2.1.

@simboss let me know what you think, so that we can proceed.

**Comment by afabiani** [comment] 2021-04-21 11:18
For the sake of completeness, find below the differences between the current GWC configuration on the GeoServer-ext DATA folder and a 1.18 vanilla one (after having saved the Caching Defaults by adding the 3857 gridset too).

```diff
--- C:\Work\geoserver-geonode-ext\geoserver\data\geonode_v218x\gwc\geowebcache.xml	2021-04-21 13:07:48.000000000 +0200
+++ C:\Apps\apache-tomcat-9.0.45\webapps\geoserver\data\gwc\geowebcache.xml	2021-04-21 13:14:41.000000000 +0200
@@ -1,75 +1,15 @@
 <?xml version="1.0" encoding="utf-8"?>
-<gwcConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://geowebcache.org/schema/1.14.0 http://geowebcache.org/schema/1.14.0/geowebcache.xsd" xmlns="http://geowebcache.org/schema/1.14.0">
-  <version>1.14.0</version>
+<gwcConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://geowebcache.org/schema/1.17.0 http://geowebcache.org/schema/1.17.0/geowebcache.xsd" xmlns="http://geowebcache.org/schema/1.17.0">
+  <version>1.17.0</version>
   <backendTimeout>120</backendTimeout>
   <blobStores/>
   <gridSets>
     <gridSet>
-      <name>InspireCRS84Quad</name>
-      <description>Every layer offered by a INSPIRE WMTS should use the InspireCRS84Quad Matrix Set</description>
-      <srs>
-        <number>4326</number>
-      </srs>
-      <extent>
-        <coords>
-          <double>-180.0</double>
-          <double>-90.0</double>
-          <double>180.0</double>
-          <double>90.0</double>
-        </coords>
-      </extent>
-      <alignTopLeft>false</alignTopLeft>
-      <resolutions>
-        <double>0.703125</double>
-        <double>0.3515625</double>
-        <double>0.17578125</double>
-        <double>0.087890625</double>
-        <double>0.0439453125</double>
-        <double>0.02197265625</double>
-        <double>0.010986328125</double>
-        <double>0.0054931640625</double>
-        <double>0.00274658203125</double>
-        <double>0.001373291015625</double>
-        <double>6.866455078125E-4</double>
-        <double>3.433227539062E-4</double>
-        <double>1.716613769531E-4</double>
-        <double>8.58306884766E-5</double>
-        <double>4.29153442383E-5</double>
-        <double>2.14576721191E-5</double>
-        <double>1.07288360596E-5</double>
-        <double>5.3644180298E-6</double>
-      </resolutions>
-      <metersPerUnit>111319.49079327358</metersPerUnit>
-      <pixelSize>2.8E-4</pixelSize>
-      <scaleNames>
-        <string>InspireCRS84Quad:0</string>
-        <string>InspireCRS84Quad:1</string>
-        <string>InspireCRS84Quad:2</string>
-        <string>InspireCRS84Quad:3</string>
-        <string>InspireCRS84Quad:4</string>
-        <string>InspireCRS84Quad:5</string>
-        <string>InspireCRS84Quad:6</string>
-        <string>InspireCRS84Quad:7</string>
-        <string>InspireCRS84Quad:8</string>
-        <string>InspireCRS84Quad:9</string>
-        <string>InspireCRS84Quad:10</string>
-        <string>InspireCRS84Quad:11</string>
-        <string>InspireCRS84Quad:12</string>
-        <string>InspireCRS84Quad:13</string>
-        <string>InspireCRS84Quad:14</string>
-        <string>InspireCRS84Quad:15</string>
-        <string>InspireCRS84Quad:16</string>
-        <string>InspireCRS84Quad:17</string>
-      </scaleNames>
-      <tileHeight>256</tileHeight>
-      <tileWidth>256</tileWidth>
-      <yCoordinateFirst>false</yCoordinateFirst>
-    </gridSet>
-    <gridSet>
       <name>EPSG:3857</name>
+      <description>This well-known scale set has been defined to be compatible with Google Maps and Microsoft Live Map projections and zoom levels. Level 0 allows representing the whole world in a single 256x256 pixels. The next level represents the whole world in 2x2 tiles of 256x256 pixels and so on in powers of 2. Scale denominator is only accurate near the equator.</description>
       <srs>
         <number>3857</number>
       </srs>
       <extent>
         <coords>
           <double>-2.003750834E7</double>
@@ -99,40 +39,58 @@
         <double>2.388657133579254</double>
         <double>1.194328566789627</double>
         <double>0.5971642833948135</double>
         <double>0.2985821416974068</double>
         <double>0.1492910708487034</double>
         <double>0.0746455354243517</double>
+        <double>0.0373227677121758</double>
+        <double>0.0186613838560879</double>
+        <double>0.009330691928044</double>
+        <double>0.004665345964022</double>
+        <double>0.002332672982011</double>
+        <double>0.0011663364910055</double>
+        <double>5.831682455027E-4</double>
+        <double>2.915841227514E-4</double>
+        <double>1.457920613757E-4</double>
       </resolutions>
       <metersPerUnit>1.0</metersPerUnit>
       <pixelSize>2.8E-4</pixelSize>
       <scaleNames>
-        <string>EPSG:3857:0</string>
-        <string>EPSG:3857:1</string>
-        <string>EPSG:3857:2</string>
-        <string>EPSG:3857:3</string>
-        <string>EPSG:3857:4</string>
-        <string>EPSG:3857:5</string>
-        <string>EPSG:3857:6</string>
-        <string>EPSG:3857:7</string>
-        <string>EPSG:3857:8</string>
-        <string>EPSG:3857:9</string>
-        <string>EPSG:3857:10</string>
-        <string>EPSG:3857:11</string>
-        <string>EPSG:3857:12</string>
-        <string>EPSG:3857:13</string>
-        <string>EPSG:3857:14</string>
-        <string>EPSG:3857:15</string>
-        <string>EPSG:3857:16</string>
-        <string>EPSG:3857:17</string>
-        <string>EPSG:3857:18</string>
-        <string>EPSG:3857:19</string>
-        <string>EPSG:3857:20</string>
-        <string>EPSG:3857:21</string>
+        <string>EPSG:900913:0</string>
+        <string>EPSG:900913:1</string>
+        <string>EPSG:900913:2</string>
+        <string>EPSG:900913:3</string>
+        <string>EPSG:900913:4</string>
+        <string>EPSG:900913:5</string>
+        <string>EPSG:900913:6</string>
+        <string>EPSG:900913:7</string>
+        <string>EPSG:900913:8</string>
+        <string>EPSG:900913:9</string>
+        <string>EPSG:900913:10</string>
+        <string>EPSG:900913:11</string>
+        <string>EPSG:900913:12</string>
+        <string>EPSG:900913:13</string>
+        <string>EPSG:900913:14</string>
+        <string>EPSG:900913:15</string>
+        <string>EPSG:900913:16</string>
+        <string>EPSG:900913:17</string>
+        <string>EPSG:900913:18</string>
+        <string>EPSG:900913:19</string>
+        <string>EPSG:900913:20</string>
+        <string>EPSG:900913:21</string>
+        <string>EPSG:900913:22</string>
+        <string>EPSG:900913:23</string>
+        <string>EPSG:900913:24</string>
+        <string>EPSG:900913:25</string>
+        <string>EPSG:900913:26</string>
+        <string>EPSG:900913:27</string>
+        <string>EPSG:900913:28</string>
+        <string>EPSG:900913:29</string>
+        <string>EPSG:900913:30</string>
       </scaleNames>
       <tileHeight>256</tileHeight>
       <tileWidth>256</tileWidth>
       <yCoordinateFirst>false</yCoordinateFirst>
     </gridSet>
   </gridSets>
   <layers/>
 </gwcConfiguration>
```

**Comment by simboss** [comment] 2021-04-21 11:57
I like what I see.
So the plan I suggest is:
- @afabiani to create a jira on GS/GWC to reproduce the issue
- @afabiani to introduce the workaround in GN 
- @afabiani to clean the GS config we ship with GN
- we release 3.2

meanwhile we fix the GS/GWC issue and we introduce this fix in 3.2.1.
Opinions?

**Comment by giohappy** [comment] 2021-04-21 12:24
> Opinions?

we all agree @simboss, our plan is the same :)

**Comment by simboss** [comment] 2021-04-21 12:27
cool,
let me reinforce that the following item is a blocker for the rest so it sould go first.

_@afabiani to create a jira on GS/GWC to reproduce the issue_

**Comment by afabiani** [comment] 2021-04-21 13:20
@simboss @giohappy I am able to reproduce the issue with a vanilla GeoServer too. 

It is an issue related to the Importer plugin, no matter of what configuration of GWC and GridSets we are using.
By importing a layer through the Importer plugin, the GridSets bound of the TiledLayer are wrong.

Notice that in my tests I added **only** the Importer plugin to a vanilla GeoServer WAR.

**Comment by simboss** [comment] 2021-04-21 13:25
@afabiani thx, open a detailed JIRA and I will have someone form the GeoServer team chew it.

**Comment by afabiani** [comment] 2021-04-21 13:32
@giohappy @simboss 

JIRA Issue created: [GEOS-10031](https://osgeo-org.atlassian.net/browse/GEOS-10031)

**Comment by giohappy** [comment] 2021-04-22 07:55
I report here the command that can be run to fix existing layers (assuming GeoNode is updated with the code fix)

`python manage.py set_all_layers_metadata -d`

This will force the re-calculation of the bounds.

**Comment by aaime** [comment] 2021-04-22 09:05
I see this issue is assigned to me, but looks like you are going ahead with a fix on the GeoNode side. Do I need to have a look at anything here? If so, it looks like it's dependent on a specific GWC configuration, how do I reproduce the issue?

**Comment by simboss** [comment] 2021-04-22 09:10
@afabiani created a [jira](GEOS-10031) for this which should give you all the details you need.

We will include this in the next GeoNode release, that is why we are working around this. We can't afford to test another GeoServer upgrade.

**Comment by giohappy** [comment] 2021-05-05 11:01
@aaime I see the [Jira](https://osgeo-org.atlassian.net/browse/GEOS-10031) is marked resolved. Is it already backported to 2.18.x?

**Comment by aaime** [comment] 2021-05-05 12:06
@giohappy ticket says it is:

![image](https://user-images.githubusercontent.com/325433/117138199-f7e5a500-adaa-11eb-83fb-ba2b9ef93efa.png)

GitHub agrees:

![image](https://user-images.githubusercontent.com/325433/117138240-0a5fde80-adab-11eb-8c50-fb4e95f2f594.png)

**Closed** 2021-05-05 14:12 UTC
Labels: GWC, investigation
