### ISSUE TITLE
Layers caching problem

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode#843] opened 2021-06-18 13:52 UTC
The layer panes are set to 512 by default but the configuration for the cache in GWC is not active and the following dridsets: EPSG: 900913x2 and EPSG: 4326x2 should be set by default when a layer is loaded

**Comment by giohappy** [comment] 2021-06-18 15:00
Since the tile size configuration comes from [GeoNode settings](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1395), we need to create a dictionay of mappings between sizes and gridsets. In case a the size set doesn't fit with a preconfigured gridset the cache will be bypassed.

**Comment by giohappy** [comment] 2021-06-21 08:55
@mattiagiupponi as agreed this is what we should do:

1 - check if 900913x2 and 4326x2 gridsets are configured on your Geoserver's GWC (Tile Caching -> Gridsets)
2 - check wether disabling the [toggle_layer_cache](https://github.com/GeoNode/geonode/blob/347a2053d179721b3dec53410d67757a563114d1/geonode/security/utils.py#L621) makes Geoserver enable all the available gridsets for that layer. Currently only three gridsets ((3857, 900913, 4326)) are configured for new layers uploaded from GeoNode.
3 - if the previous check works go to point 4, otherwsie investigate what prevents the configuration of the other gridsets for new layers
4 - the latest GWC should have fixed the need to disable the caching when a geolimit is configured on a Geofence rule. To test this, 
  - keep the `toggle_layer_cache` disabled
  - assign a geolimit on a layer to a non-admin user
  - authenticate with that user
  - check if the cache is hit. (`geowebcache-cache-result` and `geowebcache-miss-reason` response headers)
  - 
 If point 4 is confirmed we can remove `toggle_layer_cache`.

**Comment by mattiagiupponi** [comment] 2021-06-23 14:58
Both fixes are merged (master and 3.2.x)

**Closed** 2021-06-24 08:18 UTC
Labels: Geonode, backport 3.2.x, bug
