### ISSUE TITLE
Tiles caching for existing layers

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/geonode#844] opened 2021-06-18 16:11 UTC
In the demos, change the tile cache setting for existing layers, they must have 512x512 tiles by default.

Related to #843

**Comment by giohappy** [comment] 2021-08-31 09:17
@ElenaGallo do you mean changing the settings from the layer settings inside the TOC?

In that case the settings won't be saved, since settings are only saved for maps. Those settings are going to be removed from the TOC for GeoNode master, but we might consider to hide the option for 3.3.x too.

**Comment by ElenaGallo** [comment] 2021-08-31 09:43
@giohappy yes, I mean the settings from the layer settings inside the TOC

**Comment by giohappy** [comment] 2021-08-31 09:51
I have created a ticket for an investigation: https://github.com/GeoNode/geonode-mapstore-client/issues/487
I'm going to close this since it's not a bug.

**Closed by giohappy** 2021-08-31 09:51 UTC
Labels: bug, backport 3.2.x, Geonode
